config/routes.rb
  
  
  
  
  
  

  
  
  
  

Rails.application.routes.draw do
  devise_for :providers
  devise_for :users
  devise_for :admins

  root 'welcome#index'

end

app/models/provider.rb
class Provider < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :subscription
  has_many :vehicles, :dependent => :destroy
  has_many :salesmen, :dependent => :destroy

  #Enums
  enum status: [:pending, :active]
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  layout 'provider'
  before_filter :authenticate_provider!
  before_filter :authenticate_admin!, :only => [:index, :destroy, :activate, :deactivate]
  ssl_required :show, :index
  
  def index
    @providers = Provider.all.paginate(:page => params[:page], :per_page => 15)
  end
  
  def show
    @provider = current_provider
  end
  
  def destroy
    @provider = Provider.find(params[:id])
    @provider.destroy
    redirect_to(admin_providers_path(current_admin))
  end
  
  def activate
    @provider = Provider.find(params[:id])
    @provider.update_attribute(:status, "active")
  end
  
  def deactivate
    @provider = Provider.find(params[:id])
    @provider.update_attribute(:status, "pending")
  end

end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/providers/index.html.erb
<div id="content" class="span-17 colborder">
	<h4>Vos abonnés</h4>	
	<table>
		<tr>
			<th>Nom Société</th>
			<th>Nom Contact</th>
			<th>Telephone</th>
			<th>Date Abonnement</th>
			<th>Login</th>
			<th>Status</th>
			<th colspan="2">Actions</th>
		</tr>
		<% unless @providers.empty? %>
		<% @providers.each do |provider| %>
		<tr>
			<td><%= provider.company %></td>
			<td><%= provider.contact_name %></td>
			<td><%= provider.telephone %></td>
			<td><%= provider.subscription.subscription_date if subscription.date %></td>
			<td><%= provider.login %></td>
			<td><%= provider.status %></td>
			<td>
			<% if provider.pending? %>
				<%= link_to_remote("Activer", :url => activate_admin_provider_path(current_admin, provider.id)) %>
			<% else %>
				<%= link_to_remote("Désactiver", :url => deactivate_admin_provider_path(current_admin, provider.id)) %>
			<% end %>
			</td>
			<td>
				<%= link_to "Supprimer", admin_provider_path(current_admin, provider.id), :method => :delete, :confirm => "Are you sure ?" %>
			</td>
		</tr>
		<% end %>
		<% else %>
		<tr>
			<td colspan="10">Pas d'abonné pour le moment</td>
		</tr>
		<% end %>
	</table>
</div>

<div id="sidebar" class="span-6 last">
	
</div>

app/views/providers/show.html.erb
<div id="content" class="span-17 colborder">
	<%= render :partial => "shared/flash_messages" %>
	
	<% if @provider.pending? %>
		<div class="subscribe-block">
			<h2>Veuillez vérifier les informations de votre profil</h2>
		
			<p>
				Nom : <%= @provider.contact_name %><br/>
				Login : <%= @provider.login %><br/>
				Email : <%= @provider.email %><br/>
				Société : <%= @provider.company %><br/>
				Tel : <%= @provider.telephone %><br/>
				Fax : <%= @provider.fax %><br/>
				Mobile : <%= @provider.mobile if @provider.mobile %><br/>
				Adresse : <%= @provider.address %><br/>
				Code Postal : <%= @provider.zipcode %><br/>
				Ville : <%= @provider.city %><br/>
			</p>
		
			<p>
				<%= link_to "Modifier votre Compte", edit_provider_registration_path() %>
			</p>
		
			<hr/>
		
			<h3>Votre compte est suspendu, veuillez contactez le support pour le débloquer</h3>
		</div>
	
	<% else %>
	
		<div class="account">			
			<h4>Tableau de Bord</h4>
			
			<h5>Véhicules</h5>
			<p class="float_of_vehicles">
				Nombre de véhicules : <%= @provider.vehicles.count %> | <%= link_to "Ajouter un Vehicule", new_provider_vehicle_path(@provider) %> | <%= link_to "Consulter", provider_vehicles_path(@provider) %>
			</p>
			
			<h5>Commerciaux</h5>			
			<p class="salesman-team">
				Nombre de commerciaux : <%= @provider.salesmen.count %> | <%= link_to "Ajouter un commercial", new_provider_salesman_path(@provider) %> | <%= link_to "Consulter", provider_salesmen_path(@provider) %>
			</p>
			
			<h5>Statistiques</h5>
			<p>
				<!-- Prix moyen recherché :  -->
				<!-- Prix Maximum recherché : -->
				<!-- Prix minimum recherché : -->
				<!-- Kilométrage moyen recherché : -->
				<!-- Kilométrage maximum recherché : -->
				<!-- Kilométrage minimum recherché : -->
			</p>
			<p>
				<!-- Quantité moyenne de ventes par mois :  -->
				<!-- Meilleur vendeur : -->
				<!-- Plus mauvais vendeur : -->
			</p>
		</div>
	<% end %>
	
</div>
<div id="sidebar" class="span-6 last">

</div>