config/routes.rb
  
  
  
  
  
  

  
  
  
  

Rails.application.routes.draw do
  devise_for :providers
  devise_for :users
  devise_for :admins

  root 'welcome#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  before_create :verify_count
  
  private
  
  def verify_count
    return false if Admin.count >= 1
  end
end

app/models/bateau.rb
class Bateau < Vehicle
end

app/models/car.rb
class Car < Vehicle
  validates_presence_of :annee, :modele, :price, :kilometrage, :energy, :boite_vitesse,
   :on => :create, :message => "can't be blank"
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :vehicles
end

app/models/faq.rb
class Faq < ActiveRecord::Base
end

app/models/jetski.rb
class Jetski < Vehicle
end

app/models/moto.rb
class Moto < Vehicle
end

app/models/provider.rb
class Provider < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :subscription
  has_many :vehicles, :dependent => :destroy
  has_many :salesmen, :dependent => :destroy

  #Enums
  enum status: [:pending, :active]
end

app/models/salesman.rb
class Salesman < ActiveRecord::Base
  belongs_to :provider
  has_many :vehicles
  
  validates :name, uniqueness: true, on: :create
  validates :mobile_phone, uniqueness: true, on: :create
end

app/models/search.rb
class Search
  include ActiveModel::Model
  attr_accessor :minprice, :maxprice, :minkilometrage, :maxkilometrage, :minyear, :maxyear,
   :energy, :boite_vitesse, :category
  
  def vehicles
    @vehicles ||= find_vehicles 
  end
  
  private
  
  # TODO : refactor using Rails Upgrade handbook Chap. 4.4.1 - Better query composition
  # TODO : create a branch to use ElasticSearch
  def find_vehicles
    scope = Vehicle.all
    scope = scope.where("type = ?", @category) unless @category.blank?
    scope = scope.where("price >=?", @minprice) unless @minprice.blank?
    scope = scope.where("price <= ?", @maxprice) unless @maxprice.blank?
    scope = scope.where("kilometrage >= ?", @minkilometrage) unless @minkilometrage.blank?
    scope = scope.where("kilometrage <= ?", @maxkilometrage) unless @maxkilometrage.blank?
    scope = scope.where("annee >= ?", start_of_year(@minyear)) unless @minyear.blank?
    scope = scope.where("annee <= ?", end_of_year(@maxyear)) unless @maxyear.blank?
    scope = scope.where("energy = ?", @energy) unless @energy.blank?
    scope = scope.where("boite_vitesse = ?", @boite_vitesse) unless @boite_vitesse.blank?
    scope = scope.where("disponibilite = ?", true)
    scope
  end

  def start_of_year(year)
    Date.today.change(year: year.to_i).beginning_of_year
  end

  def end_of_year(year)
    Date.today.change(year: year.to_i).end_of_year
  end
end

app/models/search_profile.rb
class SearchProfile < ActiveRecord::Base
  belongs_to :user
  validates :minprice, presence: true
  validates :maxprice, presence: true
  validate :search_profile_count, on: :create

  scope :with_price_and_kilometer_criterias, ->(price,kilometrage) { where('minprice <= ? AND maxprice >= ? AND minkilometer <= ? AND maxkilometer >= ?',
      price, price, kilometrage, kilometrage) }
    
  private
  
  def search_profile_count
    errors.add(:base, 'Vous avez atteint le nombre maximum de profils. Veuillez modifier un profil existant') if SearchProfile.where(user_id: self.user_id).count == 5
  end
end

app/models/selection.rb
class Selection < ActiveRecord::Base
  belongs_to :vehicle
  belongs_to :user
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :provider
  belongs_to :plan
  has_many :payment_notifications

  enum status: [ :pending, :verified, :cancel ]
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :selections
  has_many :vehicles, :through => :selections
  has_many :search_profiles
  
  # Fetches vehicles matching the user search profiles
  # TODO : Reflect on the SearchProfile category field (Is it correct ??)
  def matching_vehicles
    vehicles = []
    self.search_profiles.each do |profile|
      found_vehicles = Vehicle.with_price_criterias(profile.category, profile.minprice, profile.maxprice)
      vehicles.concat(found_vehicles)
    end
    return vehicles
  end
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  default_scope { order("price asc") }
  validates :annee, presence: true
  validates :serialnumber, presence: true, uniqueness: true
  validates :immatriculation, presence: true, uniqueness: true
  
  belongs_to :provider
  belongs_to :salesman
  belongs_to :category
  has_many :selections
  has_many :users, :through => :selections
  
  has_attached_file :overviewpic, :styles => {:thumb => "150x150>", :medium => "250x250>", :large => "450x450>"}
  has_attached_file :frontpic, :styles => {:thumb => "150x150>", :medium => "250x250>", :large => "450x450>"}
  has_attached_file :backpic, :styles => {:thumb => "150x150>", :medium => "250x250>", :large => "450x450>"}
  has_attached_file :rfrontpic, :styles => {:thumb => "150x150>", :medium => "250x250>", :large => "450x450>"}
  has_attached_file :lfrontpic, :styles => {:thumb => "150x150>", :medium => "250x250>", :large => "450x450>"}
  has_attached_file :rbackpic, :styles => {:thumb => "150x150>", :medium => "250x250>", :large => "450x450>"}
  has_attached_file :lbackpic, :styles => {:thumb => "150x150>", :medium => "250x250>", :large => "450x450>"}
  
  # TODO : refactor this with newer twitter gem version
  # after_create :share_me
    
  # Constantes
  PRICE = [["0", "0"], ["250", "250"], ["500", "500"], ["1000", "1000"], ["1500", "1500"], ["2000", "2000"], ["2500", "2500"], ["3000", "3500"], ["4000", "4000"], ["5000", "5000"], ["6000", "6000"], ["7000", "7000"], ["8000", "8000"], ["9000", "9000"], ["10000", "10000"], ["15000", "15000"], ["20000","20000"], ["25000", "25000"], ["30000", "30000"], ["40000", "40000"], ["50000", "50000"]]
  
  KILOMETRAGE = [["10 000 Km", "10000"], ["20 000 Km", "20000"], ["30 000 Km", "30000"], ["50 000 Km", "50000"], ["70 000 Km", "70000"], ["100 000 Km", "100000"], ["150 000 Km", "150000"], ["200 000 Km", "200000"]]
  
  ENERGY = [["Essence", "Essence"], ["Diesel", "Diesel"], ["Electrique", "Electrique"], ["Hybride", "Hybride"]]
  
  VITESSE = [["Manuel", "Manuel"], ["Automatique", "Automatique"]]
  
  # Enums 
  enum energy_type: [:essence, :diesel, :electrique, :hybride]
  enum gear_box: [:manuel, :automatique]
  
  #Scopes
  scope :of_the_week, -> { where(select_for_week: true) }
  scope :sold, -> { where(disponibilite: false) }
  scope :available, -> { where(disponibilite: true) }
  scope :with_price_criterias, ->(type, minprice, maxprice) { where('type = ? AND price >= ? AND price <= ?', type, minprice, maxprice)}
  
  # TODO Move this into helper
  def display_year
    self.annee.try(:year)
  end
  
  # Fetches search_profiles based on vehicle price and kilometrage
  def matching_searchprofiles
    search_profiles = SearchProfile.with_price_and_kilometer_criterias(self.price, self.kilometrage)
    return search_profiles    
  end

  # TODO : Implement the SocialService (as a lib or model) responsible for sharing on social network
  def share_me
    SocialService.tweet(self)
    SocialService.fb_post(self)
  end
end

app/models/voiture.rb
class Voiture < Vehicle
  validates :modele, presence: true, on: :create
  validates :price, presence: true, on: :create
  validates :kilometrage, presence: true, on: :create
  validates :energy, presence: true, on: :create
  validates :boite_vitesse, presence: true, on: :create
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
	<title><%= h(yield(:title) || "GwadaOccasions") %></title>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

</body>
</html>

app/views/layouts/provider.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

	<title><%= h(yield(:title) || "GwadaOccasions") %></title>
	<%= stylesheet_link_tag 'blueprint/screen.css', 'blueprint/plugins/fancy-type/screen.css', 'base.css', :cache => true, :media => 'screen' %>
	<%= stylesheet_link_tag 'blueprint/print.css', :cache => true, :media => "print" %>
	<%= yield :script %>

	<!--[if lt IE 8]><link rel="stylesheet" href="stylesheets/blueprint/ie.css" type="text/css" media="screen, projection"><![endif]-->

	<%= javascript_include_tag 'prototype', 'effects' %>
</head>

<body>
	<div class="container">
		<div id="header" class="span-24 last">
			<ul class="menubar">
				<li><%= link_to "Accueil", root_path() %></li>
				<li><%= link_to "Catalogue", vehicles_path() %></li>
				<li>Nos Services</li>
				<li>Aide</li>
				<li>
					<% if user_signed_in? %>
						<%= link_to "Deconnexion", destroy_user_session_path() %>
					<% else %>
						<%= link_to "Connexion", new_user_session_path() %>
					<% end %>
				</li>
				<li>
					<% if provider_signed_in? %>
					 	<%= link_to "Deconnexion", destroy_provider_session_path() %>
					<% else %>
						<%= link_to "Admin", new_provider_session_path() %>
					<% end %>
				</li>
			</ul>
		</div>
		<% tabnav :provider do %>					
	    	<%= yield %>	
		<% end %>
	</div>
	<div class="subcontainer">
		&nbsp;		
	</div>
</body>
</html>

app/views/shared/_devise_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to t('devise.sessions.link'), new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to t('devise.registrations.link'), new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to t('devise.passwords.link'), new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to t('devise.confirmations.link'), new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && controller_name != 'unlocks' %>
  <%= link_to t('devise.unlocks.link'), new_unlock_path(resource_name) %><br />
<% end -%>

app/views/shared/_flash_messages.html.erb
<div id="flash_messages">
	<%= flash[:notice] if flash[:notice] %>
	<%= flash[:alert] if flash[:alert] %>
</div>

app/views/shared/_twitter.html.erb
	<div class="twitter">
		<span>Suivez nos annonces sur :</span> <br/>
		<a href="http://www.twitter.com/gwadaoccasions"><img src="http://twitter-badges.s3.amazonaws.com/twitter-b.png" alt="Follow gwadaoccasions on Twitter"/></a>
	</div>

app/views/widgets/_provider_tabnav.html.erb
<%  
# this partial renders a tabnav, you can call it in your views with:
#   <%= tabnav :provider % > (just the tabnav) 
# or, if you want a boxed tabnav:
#   <% tabnav :provider do % >
#     your html here
#   <% end % >
# (remove the space between % and >, we don't want to mess up your brand new tabnav :-))
#
# you can pass render_tabnav a few options:
#   :generate_css => true|false #=> generates a default inline css for the tabnav, defaults to false
#   :html => aHash #=> sets html options for the tabnav's div (es :html => {:class=> 'myCssClass', :id=>'myCssId'}) 
#     
render_tabnav :provider, 
              :generate_css => false do 
    
  # this generates a tab for every controller in your app
  # you'll probably want to delete this and
  # add tabs one by one as shown below
  # controller_names.each do |name|
  #   add_tab do |t|
  #     t.named name.camelize
  #     t.titled "Go to #{name.camelize}"
  #     t.links_to :controller => name
  #   end
  # end 

  add_tab do |t|
   	t.named 'Mon compte'
   	t.links_to provider_path(current_provider) if current_provider
  end
  
  add_tab do |t|
	t.named 'Vehicules'
	t.links_to provider_vehicles_path(current_provider) if current_provider
  end

  add_tab do |t|
	t.named 'Commerciaux'
	t.links_to provider_salesmen_path(current_provider) if current_provider
  end
  #
  #add_tab do |t|
  #  t.named 'Customers'
  #  t.links_to :controller => 'customers'
  #end
  #  
  # # A tab can be initialized with a Hash like this:
  # 
  # add_tab :name => 'welcome', :link => {:controller=>'welcome'}
  #
  # # You can have a dynamic name or link 
  # # (this partial is evaluated in the page context, so it sees every helper or instance variable)
  #  
  # add_tab do |t|
  #   t.named "#{current_user} details"
  #   t.links_to :controller => 'users', :action => 'show', :id => current_user.id
  # end
  #
  # # You can have an image inside 
  #
  # add_tab do |t|
  #   t.named image_tag('test')
  #   t.links_to :controller => 'users', :action => 'show', :id => current_user.id
  # end
end 
%>